# Generated by Django 5.0.3 on 2024-05-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0002_captain_classrepresentative_deputycaptain_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("total_vote", models.IntegerField(default=0)),
                (
                    "voters",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("total_vote", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="voteapp.category",
                    ),
                ),
                (
                    "voters",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Captain",
        ),
        migrations.DeleteModel(
            name="ClassRepresentative",
        ),
        migrations.DeleteModel(
            name="DeputyCaptain",
        ),
        migrations.DeleteModel(
            name="DiningHallCaptain",
        ),
        migrations.DeleteModel(
            name="EnvironmentCaptain",
        ),
        migrations.DeleteModel(
            name="GamesCaptain",
        ),
    ]
